- workers/unity/Assets/Fps/Prefabs/HealthPickup.prefab
- workers/unity/Assets/Fps/Resources/Prefabs/UnityClient/Authoritative/Player.prefab
- workers/unity/Assets/Fps/Resources/Prefabs/UnityClient/NonAuthoritative/Player.prefab
- workers/unity/Assets/Fps/Resources/Prefabs/UnityGameLogic/Player.prefab
- workers/unity/Assets/Fps/Scripts/Editor/Improbable.Fps.Editor.asmdef
-------
Minor changes to make the tutorial flow smoothly.
Followed the tutorial starting from this setup.
> Setup for health pickups tutorial

- cloud_launch_large.json
Update deployment template to `medium_small` when template update has been pushed upstream.
-------
Describe your changes here.
> Update deployment template in cloud_launch_large

- workers/unity/Assets/Fps/Resources/Prefabs/UnityClient/Authoritative/Player.prefab
- workers/unity/Assets/Fps/Resources/Prefabs/UnityClient/NonAuthoritative/Player.prefab
- workers/unity/Assets/Fps/Scripts/GameLogic/Animation/FpsAnimator.cs
Replace the MoveTowards lerp with a real lerp - use Duration, rather than speed to move to a new value.
> Replace MoveTowards with Lerp

- README.md
-------
Changed readme to point to welcome page since it provides a nicer starting point for new users.
> Changed readme to point to welcome page

- scripts/powershell/setup.ps1
- scripts/shell/setup.sh
-------
See https://brevi.link/shell-script-improvement-ticket
- Make shell.sh use the chosen option
- Add notice of what the script is going to do as soon as possible
- Preview URIs for HTTPS and SSH options
Tested locally:
.sh:
.ps:
Also tested the SSH option for bash, it used the correct choice for the remote
None
> Shell script improvements

- workers/unity/Assets/Fps/Scripts/GameLogic/FpsDriver.cs
Use a coroutine to retry respawn command, also prevent multiple commands being send by mashing the spacebar
> Add Debounce and Retries to respawn screen

- workers/unity/Packages/com.improbable.gdk.movement/Schema/movement.schema
-----
Minor issue from Daniel's feedback:
> from_gdk_packages/com.improbable.gdk.movement/movement.proto: warning: Import from_gdk_packages/com.improbable.gdk.core/common.proto but not used.
Codegen produces valid output, no complaints
> Remove unused import

- workers/unity/ProjectSettings/GraphicsSettings.asset
- workers/unity/ProjectSettings/QualitySettings.asset
Some changes made by Matt BS regarding the quality settings used, and what they do.
(For instance, lowering the texture qualities, and changing the shadow modes for lower quality settings)
> First pass at different quality modes

- workers/unity/Assets/Fps/Prefabs/Ragdoll.prefab
Boxes are cheaper than capsules, and more fitting, due to being a robot now. Also made them thinner, to fix the issue of the ragdoll's hands and feet hovering above the floor.
Now looks like this:
> Replace ragdoll capsules with (thinner) cubes

- workers/unity/Assets/Fps/Prefabs/GameLogicWorker.prefab
- workers/unity/Assets/Fps/Prefabs/SimulatedPlayerCoordinatorWorker.prefab
- workers/unity/Assets/Fps/Resources/Prefabs/SimulatedPlayer/SimulatedPlayer.prefab
- workers/unity/Assets/Fps/Scenes/FPS-Development.unity
- workers/unity/Assets/Fps/Scenes/FPS-GameLogic.unity
- workers/unity/Assets/Fps/Scenes/FPS-SimulatedPlayerCoordinator.unity
- workers/unity/Assets/Fps/Scripts/SetupLogic/SimulatedPlayerCoordinatorWorkerConnector.cs
- workers/unity/Assets/Fps/Scripts/SimulatedPlayer/SimulatedPlayerDriver.cs
- workers/unity/spatialos.SimulatedPlayer.worker.json
1. AI fixes to simulated players. Attempt to get back onto the navmesh if they get lost. Give up and respawn if they don't move for a while.
1. Reduce interest radius of simulated players.
1. Updates to use new level prefabs.
> Fix/Simulated Players

- workers/unity/spatialos.SimulatedPlayer.worker.json
- workers/unity/spatialos.SimulatedPlayerCoordinator.worker.json
- workers/unity/spatialos.UnityGameLogic.worker.json
-------
Describe your changes here.
> running gamelogic worker always in headless

- workers/unity/Assets/Fps/Art/Character/Robot/Textures/FPS_Robot_CLR.png.meta
- workers/unity/Assets/Fps/Art/Character/Robot/Textures/FPS_Robot_LOD_CLR.png.meta
- workers/unity/Assets/Fps/Art/Character/Robot/Textures/FPS_Robot_LOD_MSK.tif.meta
- workers/unity/Assets/Fps/Art/Character/Robot/Textures/FPS_Robot_LOD_NMT.png.meta
- workers/unity/Assets/Fps/Art/Character/Robot/Textures/FPS_Robot_LOD_ORM.tif.meta
- workers/unity/Assets/Fps/Art/Character/Robot/Textures/FPS_Robot_MSK.tif.meta
- workers/unity/Assets/Fps/Art/Character/Robot/Textures/FPS_Robot_NMT.png.meta
- workers/unity/Assets/Fps/Art/Character/Robot/Textures/FPS_Robot_ORM.tif.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/clouds_CLR.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/floor_square_CLR.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/floor_square_NMT.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/grid_terrain_NMT.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/pickup_cube_CLR.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/projected_grid_CLR.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/projected_grid_NMT.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/projected_grid_blank_CLR.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/projected_grid_glossy_CLR.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/projected_grid_side_CLR.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/projected_grid_variant_CLR.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/sprite_spark_CLR.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/target_CLR.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/target_NMT.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/trim_CLR.png.meta
- workers/unity/Assets/Fps/Art/Weapon/Gun_Assault/Textures/Assault_Rifle_CLR.png.meta
- workers/unity/Assets/Fps/Art/Weapon/Gun_Assault/Textures/Assault_Rifle_MSK.tif.meta
- workers/unity/Assets/Fps/Art/Weapon/Gun_Assault/Textures/Assault_Rifle_NMT.png.meta
- workers/unity/Assets/Fps/Art/Weapon/Gun_Assault/Textures/Assault_Rifle_ORM.tif.meta
Final assembly size is now HALF the size it was before the new textures and settings!
> Tweaked texture compression settings with Matthew

- workers/unity/ProjectSettings/ProjectSettings.asset
-------
Describe your changes here.
> fix naming

- LICENSE.md
-------
SpatialOS GDK for Unity instead of Unity GDK
> updating name in license

- workers/unity/Assets/Fps/Scripts/MetricSendSystem.cs
-------
* redo load calculation
* simplify fps calculation
* add fps and unity heap use to sent metrics
Playground: https://github.com/spatialos/gdk-for-unity/pull/606
FPS Starter Project: https://github.com/spatialos/gdk-for-unity-fps-starter-project/pull/62
Blank Project: https://github.com/spatialos/gdk-for-unity-blank-project/pull/13
ran a deployment and looked at the numbers/charts
If your change will take …
> UTY-1376: update metric send system

- CHANGELOG.md
-------
updating changelog
CI
changelog
> Add metric system changes to changelog

- CHANGELOG.md
> Changelog wording

- ci/build.sh
- gdk.pinned
made it simpler & added Android build
ran it locally, need to test on TeamCity
> Update build script

- workers/unity/Assets/Fps/Art/UI/Animations/FailedRespawn.anim
- workers/unity/Assets/Fps/Resources/Prefabs/MobileClient/Authoritative/Player.prefab
- Made connect button interactable whenever player spawn would fail. Before that you had to press Space, which doesn't really work on mobile
- remove duplicate MobileControls MB from Player
ran it locally and tested the different scenes
> fixing UI and removed duplicate MB

- workers/unity/Packages/com.improbable.gdk.deploymentlauncher/DeploymentLauncher.cs
Added a GUI Spinner to the Deployment Launcher to indicate that it's doing things after selecting Launch.
Did a couple of test runs in the editor.
> Deployment Launcher spinner

- workers/unity/Assets/Fps/Scripts/Config/MapBuilder.cs
- workers/unity/Assets/Fps/Scripts/Editor/MapBuilderVisualisationWindow.cs
- workers/unity/Assets/Fps/Scripts/GameLogic/Respawning/SpawnPoints/SpawnPoints.cs
- workers/unity/Assets/Fps/Scripts/GameLogic/WorldTiles/TileCollapser.cs
- workers/unity/Assets/Fps/Scripts/GameLogic/WorldTiles/TileCombinedMeshProvider.cs
Fixed some errors in the new MapBuilder
Starting cloud deployment currently to test issues
No need for changelog, fixing something thats new and has its own log.
> Mapbuilder fixes

- workers/unity/Packages/com.improbable.gdk.guns/Systems/ServerShootingSystem.cs
- workers/unity/Packages/com.improbable.gdk.health/Systems/HealthRegenSystem.cs
- workers/unity/Packages/com.improbable.gdk.health/Systems/ServerHealthModifierSystem.cs
> removed reactive components

- CHANGELOG.md
- workers/unity/Assets/Fps/Config/BuildConfiguration.asset
- workers/unity/Assets/Fps/Scripts/SetupLogic/SimulatedPlayerCoordinatorWorkerConnector.cs
- Updated build configuration to work with the new build system UI
- Added additional checks to the `SimulatedPlayerWorkerCoordinator` to ensure it doesn't spam errors, if play mode is exited at the wrong time. 
tested locally in editor
> Updating build config & adding checks to SimulatedPlayerWorkerCoordinatorConnector

- ci/launch.sh
pass in region code
as we'll be in the UK for QA, we will use the EU region
buildkite
n/a
> Fix release-qa pipeline by passing in region code to deployment launcher

- workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Blank_M.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Default_M.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Default_N.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Foliage_M.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Glossy_M.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Top_M.png.meta
- workers/unity/Assets/Fps/Art/Materials/Textures/T_Projected_Variant_M.png.meta
- workers/unity/Assets/Fps/Resources/Prefabs/MobileClient/Authoritative/Player.prefab
- workers/unity/Assets/Fps/Resources/Prefabs/UnityClient/Authoritative/Player.prefab
- workers/unity/Assets/Fps/Scenes/FPS-Development.unity
- workers/unity/ProjectSettings/QualitySettings.asset
Shadow fixes by Matt and Jess
simplayer will be fixed by https://github.com/spatialos/gdk-for-unity-fps-starter-project/pull/137
n/a
> Fix shadow issues

- workers/unity/Assets/Fps/Config/PostProcessing/Global Post-processing Profile.asset
- workers/unity/ProjectSettings/GraphicsSettings.asset
Use forward render pipeline
Disable screen space reflections
Fixed incompatible render settings for mac
Tested in editor, will test for cloud
> Fix mac rendering

- workers/unity/Assets/Fps/Scripts/SetupLogic/iOSWorkerConnector.cs
include Core
ran client, connected to cloud and local deployments
n/a
> Include core in iOSWorkerConnector 

- workers/unity/Assets/Fps/Scenes/FPS-Development.unity
- updated navmesh to match latest map generated by the map builder
- removed unnecessary FPS-Visualisation objects from scenes
n/a
> Rebuild navmesh with latest mapbuilder

- .buildkite/premerge.steps.yaml
- .buildkite/release-qa.steps.yaml
Looks like we forgot to change them both.
> Bump BK queue ID

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.standardtypes/package.json
Fix package dependencies
Quick bug fix in compile order
Tested fresh import, confirmed it now only compiles twice (once before and once after code gen)
Where previously this was 3 times.
> Fix package dependency

- .buildkite/premerge.steps.yaml
- .buildkite/release-qa.steps.yaml
- workers/unity/Packages/manifest.json
- workers/unity/ProjectSettings/ProjectSettings.asset
- workers/unity/ProjectSettings/ProjectVersion.txt
Changes from the upgrade - will update with a new BK agent queue when that's done.
> Unity 2018.3.11 upgrade

- CHANGELOG.md
Update changelog with latest FPS changes
n/a
n/a
> Update changelog with latest FPS changes

- .buildkite/hooks/post-checkout
- .buildkite/premerge.steps.yaml
- .buildkite/release-qa.steps.yaml
- ci/bootstrap.sh
Fixing buildkite. Unsure what will happen with the `gdk-for-unity` clone, it may work? It may not? May need to do a bit of debugging.
> Fix BuildKite

- workers/unity/Assets/Fps/Prefabs/AndroidClientWorker.prefab
- workers/unity/Assets/Fps/Prefabs/UI/OnScreenUI_Mobile.prefab
- workers/unity/Assets/Fps/Scenes/FPS-AndroidClient.unity
- workers/unity/Assets/Fps/Scripts/GameLogic/StateMachine/Default/DefaultConnectState.cs
- workers/unity/Assets/Fps/Scripts/GameLogic/StateMachine/Default/DefaultPlayState.cs
- workers/unity/Assets/Fps/Scripts/GameLogic/StateMachine/Default/DefaultSpawnState.cs
- workers/unity/Assets/Fps/Scripts/GameLogic/StateMachine/Default/DefaultState.cs
- workers/unity/Assets/Fps/Scripts/GameLogic/StateMachine/Default/DisconnectedState.cs
- workers/unity/Assets/Fps/Scripts/GameLogic/StateMachine/Default/DisconnectedState.cs.meta
- workers/unity/Assets/Fps/Scripts/SetupLogic/SimulatedPlayerWorkerConnector.cs
- workers/unity/Assets/Fps/Scripts/UI/FpsUIButton.cs
Adding proper disconnect logic and ensuring different ways of failing to connect / spawn a player still work correctly.
added some smaller drive-by fixes
tested locally. planning a cloud mobile test later
> Add visual responses to disconnect into default flow

- CHANGELOG.md
- workers/unity/Assets/Fps/Prefabs/Cameras/FirstPersonCamera_mobile.prefab
- workers/unity/ProjectSettings/QualitySettings.asset
disabling anti-aliasing for mobile, because it still looks exactly the same and improves performance.
ran it on the phone and checked how it looked 
> Disable anti-aliasing for mobile

- .buildkite/premerge.steps.yaml
- .buildkite/release-qa.steps.yaml
Its that time of day - this queue has more logs being forwarded to Kibana for better debug + tracking.
> BK new queue

- .buildkite/premerge.steps.yaml
- .buildkite/release-qa.steps.yaml
> Buildkite mobile labels

- CHANGELOG.md
- workers/unity/Assets/Fps/Scripts/GameLogic/Animation/FpsAnimator.cs
- workers/unity/Assets/Fps/Scripts/GameLogic/FpsDriver.cs
The gun wouldn't appear until you rotate the player enough.
> Fix animation of gun

- .buildkite/hooks/post-command
- ci/launch.sh
- workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/DeploymentLauncher.csproj
Updated the release QA launch scripts to use the new deployment launcher CLI. 
Commented out BK sections and ran locally. Worked fine. Once this branch is rebased to have the BK fixes, will run on there.
N/A 
> Update release QA scripts

- workers/unity/Assets/Fps/Scenes/FPS-GameLogic.unity
- workers/unity/Assets/Fps/Scripts/Config/MapBuilder.cs
- workers/unity/Assets/Fps/Scripts/GameLogic/WorldTiles/TileTypeCollection.cs
- workers/unity/Assets/Fps/Scripts/WorldTiles/MapTemplate.cs
- workers/unity/Assets/Fps/Scripts/WorldTiles/TileCollapser.cs
- workers/unity/Assets/Resources.meta
Map generation is Async again using Coroutines.
Fixed map generation in Development scene when async.
Map is now build in a temporary scene during generation, to avoid intermittend physics updates.
Tested on Mobile and pc, works in Development scene.
Needs changelog
@jessicafalk
> Optimize map generation

- CHANGELOG.md
- default_launch.json
`small` -> `w2_r0500_e5` 
Local deploy.
Release note.
> UTY-2058: Update launch config templates

- CHANGELOG.md
Added entry for fixed known crash issue
Add PR/Issue links to all entries.
> Update changelog link

- workers/unity/Assets/Fps/Scripts/Config/MapBuilder.cs
Refactored some bits of the map builder to work in both the editor and play mode again.
Testing in a stand alone build atm
> Fix mapbuilder in editor

- workers/unity/ProjectSettings/BurstAotSettings_Android.json
- workers/unity/ProjectSettings/BurstAotSettings_StandaloneLinux.json
- workers/unity/ProjectSettings/BurstAotSettings_StandaloneOSX.json
- workers/unity/ProjectSettings/BurstAotSettings_StandaloneWindows.json
- workers/unity/ProjectSettings/BurstAotSettings_iOS.json
> disabled burst compilation

- workers/unity/Assets/Fps/Scripts/SetupLogic/MobileWorkerConnector.cs
Mobile connector now uses Dev Auth Token passed along as argument
Tested
> Fix mobile DAT flow

- ci/launch.sh
> Fix launch scripts

- .buildkite/premerge.steps.yaml
The bug that affected this should have been fixed in 2019.1.8f1 or something like that
> Re-enable IL2CPP builds

- .buildkite/hooks/post-checkout
- .buildkite/hooks/pre-command
- .buildkite/premerge.steps.yaml
- ci/test.sh
Basically the same PR as https://github.com/spatialos/gdk-for-unity/pull/1154. We have tests here too!
> Add test failure reporting

- .buildkite/premerge.steps.yaml
- .buildkite/release-qa.steps.yaml
> Buildkite queue update

- CHANGELOG.md
- workers/unity/ProjectSettings/ProjectSettings.asset
Update app identifiers to match io.improbable.*
buildkite
> Update app identifiers to match io.improbable.*

- CHANGELOG.md
- gdk.pinned
- workers/unity/Assets/Fps/Scripts/Config/FpsEntityTemplates.cs
- update FPS with breaking change from https://github.com/spatialos/gdk-for-unity/pull/1315
> Pass EntityId into Player EntityTemplate method

- CHANGELOG.md
- gdk.pinned
- workers/unity/Assets/Fps/Scripts/Config/AdvancedEntityPipeline.cs
Take in changes from https://github.com/spatialos/gdk-for-unity/pull/1333
> Better gameobject initialization

- ci/bootstrap.sh
- ci/get-shared-ci.sh
- ci/launch.sh
- ci/lint.sh
- ci/shared-ci.pinned
- ci/test.sh
As per the guide in https://improbableio.atlassian.net/browse/UTY-2600
> New Buildkite instrumentation format

- .buildkite/premerge.steps.yaml
Update queue to v4-20-07-06-120608-bk13080-eb89af6c. [Bake Link] (https://buildkite.com/improbable/platform-bakery/builds/13080)
Pre-merge build
> UTY-2607: update linux queues

- .buildkite/premerge.steps.yaml
- .buildkite/release-qa.steps.yaml
> UTY-2657: set max agents

- gdk.pinned
- workers/unity/Assets/Fps/Scripts/Health/Systems/HealthRegenSystem.cs
- workers/unity/Assets/Fps/Scripts/Movement/Behaviours/ProxyMovementDriver.cs
Updated game code for breaking changes in GDK
> Updated game code for new API's without View
