spatialos/gdk-for-unity-fps-starter-project

workers/unity/Packages/com.improbable.gdk.guns/Behaviours/ShotRenderer.cs

A tentative bug fix for some linerenderers remaining in the world. (Coroutines are stopped, so if a player is removed, their existing bullets would not be sent back to the pool)
This hasn't been tested in a deployment yet.

remove all bullets if player disabled/removed

---

workers/unity/ProjectSettings/EditorBuildSettings.asset

(Still uses FakeClient scene, despite it not existing)
- This is a generated change that I get when I attempt to build. I guess it was missing from the Simulated Players commit?

hotfix - Update build settings

---

workers/unity/Assets/Fps/Art/AnimationControllers/FirstPersonAnims.controller
workers/unity/Assets/Fps/Art/AnimationControllers/ThirdPersonAnims.controller
workers/unity/Assets/Fps/Scripts/GameLogic/Animation/FpsAnimator.cs
workers/unity/Assets/Fps/Scripts/GameLogic/Animation/ProxyAnimation.cs
workers/unity/Assets/Fps/Scripts/GameLogic/FpsDriver.cs
workers/unity/Packages/com.improbable.gdk.movement/Behaviours/GroundChecker.cs

- Remove the 'near ground state', since it is mostly unused.
- Reduce the jumping anim length, to fix the pauses upon landing
(To note, jumping onto and walking off small blocks looks a bit weird. We should probably check that that looks alright before pushing this in)

Remove 'near ground', fix landing anim lag

---

workers/unity/Packages/com.improbable.gdk.ragdolls/Behaviours/RagdollSpawner.cs

Currently multiple death events are being received per death.
Added a boolean flag to prevent multiple ragdolls spawning.
Ideally we would solve the root cause, but in the meantime, this is visually a very nasty bug, so a hotfix will improve the user experience in the short term.

Prevent multiple ragdolls being spawned on death

---

scripts/shell/setup.sh

If a user has MacOS and has not installed `coreutils` through `brew` they will not have `realpath`. This PR introduces a workaround for this - but at the cost of it no longer follows symlinks. This is probably okay - and the user has to provide confirmation to the path given to them.
Tested on MacOS and Git Bash
N/A
@jared-improbable @jessicafalk

MacOS Setup Script Fix

---

workers/unity/Packages/manifest.json

-------
Unity changed the dependencies of their in-built packages. That was causing all the errors when using the latest 2018.2 with the fps starter project.
Tested locally with 2018.2.13 and 2018.2.8. No errors are thrown anymore.

adding packages required for 2018.2.13 support

---

workers/unity/Packages/com.improbable.gdk.ragdolls/Behaviours/RagdollSpawner.cs

-------
Roll back Peter's masking fix now that the root cause has been resolved (https://github.com/spatialos/gdk-for-unity/pull/564)
Manual. Deployed and wasn't able to reproduce the bug anymore
None
@peterimprobable @mattyoung-improbable

UTY-1363: Rolled back double ragdoll masking code

---

CHANGELOG.md
workers/unity/Assets/Fps/Scenes/FPS-Client.unity
workers/unity/Assets/Fps/Scenes/FPS-Development.unity
workers/unity/Assets/Fps/Scenes/FPS-GameLogic.unity
workers/unity/Assets/Fps/Scenes/FPS-SimulatedPlayerCoordinator.unity
workers/unity/Packages/com.improbable.gdk.objectpooling/ObjectPooler.cs

-------
* remove `ObjectPooling` gameobject from all scenes
* create `ObjectPool` gameobject with the `ObjectPooler` monobehaviour at runtime
Simply removing the `ObjectPooler` instance from scenes results in numerous errors relating to the missing instance, so the `ObjectPooler` instance now gets created at runtime if it's found to be null when calling `GetOrCreateObjectPool<T>`.
n/a
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for …

Dynamically create ObjectPooler instance

---

CHANGELOG.md
workers/unity/Assets/Fps/Resources/Prefabs/SimulatedPlayer/SimulatedPlayer.prefab

-------
* enable rotation about the x-axis so that the `MoveTowards` method actually enables simulated players to look at targets on different heights to them
* looked at transforms in-editor when running a cloud deployment
* ran a built out client, took the higher ground, still got killed
n/a

Simulated players can now shoot targets on different planes to them

---

CHANGELOG.md
workers/unity/spatialos.SimulatedPlayer.worker.json
workers/unity/spatialos.SimulatedPlayerCoordinator.worker.json
workers/unity/spatialos.UnityClient.worker.json
workers/unity/spatialos.UnityGameLogic.worker.json

-------
We had the wrong OSX launch configuration and therefore it was not possible to start the same worker type multiple times.
Ran it locally with and tested all the external workers locally as well.

Fixing launch configuration for OSX

---

ci/pack.sh
packer.config.json

Following up from: https://github.com/spatialos/gdk-for-unity-shared-ci/pull/16 - this adds the JSON configuration and a simple CI script to invoke the Packer.
_On the road to release automation..._ 🚶 
Ran the ci script. It works happily.
Will be documented in our release process wiki.
Purely internal infrastructure - probably doesn't need one? 

Add Packer Config

---

CHANGELOG.md
cloud_launch_large.json
cloud_launch_small.json
default_launch.json
workers/unity/spatialos.SimulatedPlayerCoordinator.worker.json
workers/unity/spatialos.UnityGameLogic.worker.json

Update launch configurations to use the new Runtime.
Also updated dimensions for deployments to better match world sizes (300x300 for local/small, 900x900 for large deployments).
Local + small deployments use a 4-layer world, which has edge length of 292m. Calculated by: (4*2*36)+4. The larger deployment uses a 12-layer world, which has edge length of 868m (12*2*36)+4. This means that the spatial world sizes defined in the launch configs only need to be 300x300 and 900x900.
n/a
I have now

Use the new Runtime by default

---

CHANGELOG.md
cloud_launch_large_sim_players.json
workers/unity/Assets/Fps/Scripts/Editor/MapBuilderVisualisationWindow.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Program.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/DeploymentLauncher.cs

- added ability to choose deployment region (US, EU) [UTY-1819]
- added ability to force-upload assembly [UTY-1817]
- automatically open console pages when deployment(s) ready [UTY-1779]
- only opens simplayer console page if simplayers are enabled
- reduced `fps_simulated_players_creation_interval` from 60 to 5 [UTY-1801]
- disabled the `Generate Map` button in the MapBuilder window if `MapBuilderSettings` is not set [UTY-1825]
- did it in editor
- logged into the created deployments
- changelog 👍 
- docs PR: https://github.com/spatialos/gdk-for-unity/pull/797

Deployment Launcher tweaks

---

CHANGELOG.md
workers/unity/Assets/Fps/Scenes/FPS-Development.unity
workers/unity/Assets/Fps/Scripts/Config/PlayerHealthSettings.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/ClientWorkerHandler.cs

The navmesh was applied to the client world instead of the simulated player world.
Swapped the position of the two worlds to ensure the navmesh gets applied to the correct world.
Reduced health regen a bit as it was nearly impossible to die
ran it in the editor.

Fixing simulated players for development scene

---

workers/unity/Assets/Fps/Scenes/FPS-Development.unity
workers/unity/Packages/com.improbable.gdk.guns/Behaviours/ShotRenderer.cs

Surrounding props are now at the right location
Bullets are now position remapped
Tested in location deployment using the Development scene (where the issue was visible)

Fixed Development scene terrain and bullets remapping

---

CHANGELOG.md
default_launch.json
workers/unity/Assets/Fps/Scripts/Config/MapBuilder.cs
workers/unity/Assets/Fps/Scripts/Editor/MapBuilderVisualisationWindow.cs
workers/unity/Assets/Fps/Scripts/GameLogic/WorldTiles/TileEnabler.cs
workers/unity/Assets/Fps/Scripts/GameLogic/WorldTiles/TileTypeCollection.cs
workers/unity/Assets/Fps/Scripts/GameLogic/WorldTiles/TileTypeVolume.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/AndroidWorkerConnector.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/ClientWorkerConnector.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/ConnectionController.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/GameLogicWorkerConnector.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/MobileWorkerConnectorBase.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/MobileWorkerConnectorBase.cs.meta
workers/unity/Assets/Fps/Scripts/SetupLogic/SimulatedPlayerCoordinatorWorkerConnector.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/WorkerConnectorBase.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/iOSWorkerConnector.cs

This PR has a few changes: 
- Drive-by cleanup of some old worker configurations.
- Made map building deferred over multiple frames instead of blocking. This stops the `SimulatedPlayerCoordinator` workers from falling over at startup and allow them to maintain a reasonable FPS such that they can respond to pings.
- Note that this does have consequences on other parts of the codebase (i.e. - cannot spawn until map is built). There is still an unresolved question of what happens if a UnityGameLogic worker goes down and starts to checkout existing players _before_ the map is built, but this is an edge case (and I expect that since we are client side auth, it will _probably_ be okay). 
- Cleaning up the structure of the worker connectors (still work to do, but they are more aligned). We now …

Clean up worker connectors + make map building deferred over frames

---

cloud_launch_large.json
cloud_launch_large_sim_players.json

Remove the `max_bridge_module_load` flag from cloud launch large configs
Will run a deployment overnight to validate performance.
n/a

Remove `max_bridge_module_load` flag

---

workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Commands/Create.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/DeploymentLauncher.csproj

- upgrade dpl launcher platform sdk to 13.7.1
- use DAT secret instead of ID
n/a
Jamie will do it when merging the main experimental branch

Use DAT secret instead of ID

---

cloud_launch_large.json
cloud_launch_small.json

Updated cloud launch templates to use the latest `w4_r1000_e10` template. Its topology is identical to that of the old template.
n/a

Update cloud launch templates

---

workers/unity/Packages/com.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs

Sorry for the stacked diff, but noticed this was super simple to do with how it is currently setup.
Closed the window = process killed.
Closed Unity = process killed.
N/A

Deployment launcher handles exits properly

---

workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Ipc.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Program.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/Assembly.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/Authentication.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/Authentication.cs.meta
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/Deployment.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/WrappedTask.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/DeploymentConfigurations.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Ipc.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/TaskManager.cs
workers/unity/Packages/com.improbable.gdk.deploymentlauncher/TaskManager.cs.meta

This PR adds the listing and stopping functionality back into the deployment launcher. We fetch more data about each deployment (start time, region, which workers are connected, and tags on the deployment) and expose a button to open the deployment in the console. 
Tested each part of the functionality. Seemed to work and report errors properly.
Coming soon
Will do a big one for the _final merge_. 
@jessicafalk @jared-improbable

Add Listing + Stopping to Deployment Launcher Rewrite

---

ci/pack.sh

Fix shell script which has `set` options in the wrong order

CI pipefail fix

---

workers/unity/Assets/Fps/Scripts/GameLogic/StateMachine/Default/DefaultPlayState.cs
workers/unity/Assets/Fps/Scripts/GameLogic/StateMachine/Default/DisconnectedState.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/AdvancedEntityPipeline.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/ClientWorkerConnector.cs
workers/unity/Assets/Fps/Scripts/SetupLogic/OneTimeInitialisation.cs

Especially on mobile it can happen that SpatialOS thinks a worker is still connected, but the server-worker heartbeats fail at some point. When that happens we delete the player entity, but not disconnect the client leaving the client in a bad state. This PR creates some callbacks to disconnect whenever we lose the player entity and go back to the start screen.
running in editor by deleting player entities via the inspector.

Adding callbacks for losing player

---

ci/bootstrap.sh
ci/shared-ci.pinned

This is defensive of a future change in the GDK to stop copying schema files around. Said change means that we no longer have to run `spatial prepare-for-run` in the worker build step. 
As different projects/branches now require different commits from the shared-ci repo, we need to pin which version we use.
n/a

Pin shared-ci version

---

CHANGELOG.md
workers/unity/Assets/Fps/Config/BuildConfiguration.asset

marked linux builds for the gamelogic worker and the simulated player coordinator worker as required to ensure that the build fails, if  you don't have linux build support installed.

Marking linux builds as required

---

CHANGELOG.md
workers/unity/Assets/Fps/Scripts/SetupLogic/MobileWorkerConnector.cs

Ordered the wrong way. Required you to fully uninstall and reinstall the app to swap between local and cloud flows

Fix Mobile Ordering

---

CHANGELOG.md
workers/unity/Packages/io.improbable.gdk.guns/Systems/ServerShootingSystem.cs

- check if gun data exists before using it
- Quick-fix for #212 
- drive-by update to changelog
- shot some pickups and no more exceptions

Fix exception when shooting health pickups

---

ci/launch.sh
gdk.pinned

As of https://github.com/spatialos/gdk-for-unity/pull/1299, the launch.sh scripts need the runtime version. This PR implements that change

Update release QA script

---

ci/bootstrap.sh

Fix "unbound variable" error when running ci/bootstrap on a non-windows non-buildkite machine
hit init

 Fix "unbound variable" error in ci/bootstrap.sh

---

CHANGELOG.md
workers/unity/Assets/Fps/Scripts/WorkerConnectors/MobileWorkerConnector.cs

Changed `Kcp` to `ModularKcp`.
Sadly this is the end of the incredibly useful comment: 
> These are the last tested values

Remove deprecated network type references

---

CHANGELOG.md
gdk.pinned
workers/unity/Assets/Fps/Scripts/Editor/WorldTiles/MapBuilderVisualisationWindow.cs
workers/unity/Assets/Fps/Scripts/SimulatedPlayer/SimulatedPlayerDriver.cs
workers/unity/Assets/Fps/Scripts/WorkerConnectors/ClientWorkerConnector.cs
workers/unity/Assets/Fps/Scripts/WorkerConnectors/GameLogicWorkerConnector.cs
workers/unity/Assets/Fps/Scripts/WorkerConnectors/SimulatedPlayerCoordinatorWorkerConnector.cs
workers/unity/Assets/Fps/Scripts/WorkerConnectors/WorkerConnectorBase.cs
workers/unity/Assets/Fps/Scripts/WorldTiles/Map/MapBuilder.cs

Updated the `WorkerConnector` implementations with these https://github.com/spatialos/gdk-for-unity/pull/1365 changes. Additionally made all the map building use `Task` rather than coroutines and did some refactoring.

Worker connector updates & refactoring

---

.buildkite/premerge.steps.yaml
.buildkite/release-qa.steps.yaml
ci/shared-ci.pinned
ci/test.sh

Provides `ACCELERATOR_ENDPOINT` argument to agents and provides the relevant arguments to use either the local/cloud Accelerators for mac/windows agents.
Depends on https://github.com/spatialos/gdk-for-unity-shared-ci/pull/72
Ran the pipeline. Multiple times.
n/a

Enable Accelerator

---

CHANGELOG.md
spatialos.json

- `spatialos.json` sdk and standard library version updated to `14.6.1`. [#281](https://github.com/spatialos/gdk-for-unity-fps-starter-project/pull/281)
None

UTY-2626: change sdk to 14.6.1

---

CHANGELOG.md
workers/unity/ProjectSettings/BurstAotSettings_Android.json
workers/unity/ProjectSettings/BurstAotSettings_StandaloneLinux.json
workers/unity/ProjectSettings/BurstAotSettings_StandaloneLinux64.json
workers/unity/ProjectSettings/BurstAotSettings_StandaloneOSX.json
workers/unity/ProjectSettings/BurstAotSettings_StandaloneWindows.json

UTY-2690: Enable Burst by default
